apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auto-rotation-test
spec:
  parameters:
    clientID: {{kvClientId}}
    keyvaultName: {{kvName}}
    objects: |
      array:
        - |
          objectName: cert1
          objectType: secret
    tenantId: {{kvTenantId}}
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
  provider: azure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{kvClientId}}
  name: auto-rotation-test
---
apiVersion: v1
kind: Pod
metadata:
  name: auto-rotation-test
  labels:
    azure.workload.identity/use: 'true'
spec:
  serviceAccountName: auto-rotation-test
  containers:
  - name: auto-rotation-test
    image: '{{acrName}}.azurecr.io/tests/auto-rotation-test:latest'
    volumeMounts:
    - name: certs
      mountPath: /certs
      readOnly: true
  volumes:
    - name: certs
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: auto-rotation-test
---
